[versions]
# Plugins
spring-boot = "3.5.10"
spring-dependency-management = "1.1.7"
vaadin = "24.9.6"
vaadin-plugin = "24.9.6"
spotless = "8.2.1"
errorprone-plugin = "5.0.0"
nullaway-plugin = "3.0.0"
pmd = "7.21.0"

# Dependencies
errorprone = "2.45.0"
nullaway = "0.13.1"
jspecify = "1.0.0"
google-java-format = "1.33.0"
beta-checker = "1.0"
lombok = "1.18.42"
spotbugs = "6.4.8"
spotbugs-annotations = "4.9.8"
findsecbugs = "1.14.0"

[libraries]
# Vaadin
vaadin-core = { module = "com.vaadin:vaadin-core" }
vaadin-spring-boot-starter = { module = "com.vaadin:vaadin-spring-boot-starter" }

# Spring Boot
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }

# Lombok & JSpecify
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }

# Guava
guava-beta-checker = { module = "com.google.guava:guava-beta-checker", version.ref = "beta-checker" }

# Error Prone & NullAway
errorprone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone" }
nullaway = { module = "com.uber.nullaway:nullaway", version.ref = "nullaway" }

spotbugs-annotations = { module = "com.github.spotbugs:spotbugs-annotations", version.ref = "spotbugs-annotations" }
findsecbugs = { module = "com.h3xstream.findsecbugs:findsecbugs-plugin", version.ref = "findsecbugs" }

# JUnit
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

# BOMs
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
vaadin-bom = { module = "com.vaadin:vaadin-bom", version.ref = "vaadin" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
vaadin = { id = "com.vaadin", version.ref = "vaadin-plugin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
errorprone = { id = "net.ltgt.errorprone", version.ref = "errorprone-plugin" }
nullaway = { id = "net.ltgt.nullaway", version.ref = "nullaway-plugin" }
spotbugs = { id = "com.github.spotbugs", version.ref = "spotbugs" }

[bundles]
vaadin = [
    "vaadin-core", 
    "vaadin-spring-boot-starter"
]