spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java,src/main/resources
      poll-interval: 2s
      quiet-period: 1s
      exclude: frontend/**,node_modules/**
    livereload:
      enabled: true

vaadin:
  launch-browser: false
  allowed-packages: com.vaadin,org.vaadin,com.flowingcode,com.vertyll.fastprod

api:
  backend:
    url: ${API_URL:http://localhost:8080/api/v1}

security:
  jwt:
    access-token:
      expiration: ${JWT_ACCESS_EXPIRATION:900000}
      refresh-before-expiry: ${JWT_REFRESH_BEFORE_EXPIRY:120000}
    refresh-token:
      cookie-name: "refresh_token"

server:
  port: ${SERVER_PORT:8001}

logging:
  level:
    org.atmosphere: ${LOG_LEVEL_ATMOSPHERE:WARN}
    com.vertyll.fastprod: ${LOG_LEVEL_APP:DEBUG}
    org.springframework.security: ${LOG_LEVEL_SECURITY:DEBUG}